<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$nextPage = ($_productCollection->getCurPage() == $_productCollection->getLastPageNumber()) ? 0 : $_productCollection->getCurPage(+1);
?>
<div class="mage-magictabs mc-<?php echo $this->escapeHtml($this->getTypeFilter()); ?>" data-next-page="<?php /* @escapeNotVerified */ echo $nextPage ?>">
    <?php if (!$_productCollection->count()) : ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php else : ?>
        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <?php
        $config     = $this->getWidgetCfg();
        // $width      = $config['widthImages'];
        // $height     = $config['heightImages'];
        $showCart       = $config['cart'];
        $showCompare    = $config['compare'];
        $showWishlist   = $config['wishlist'];
        $showReview     = $config['review'];
        $swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Magiccart_Magicproduct::product/listing/renderer.phtml');
        ?>
        <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product) : ?>
                    <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info per-product" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image 
                        ?>
                        <div class="images-container">
                            <?php
                            $product_label = $_aloHelper->getLabels($_product);
                            echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : '';
                            ?>
                            <div class="product-hover">
                                <?php //echo $_aloHelper->getTimer($_product); 
                                ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                                <div class="link-view">
                                    <button type="button" class="action quickview <?php echo $_product->getTypeId() ?>" title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_secure' => $this->getRequest()->isSecure())) ?>'});">
                                        <span><?= $block->escapeHtml(__('Quick view')) ?></span>
                                    </button>
                                </div>
                                <div class="hover-box">
                                    <div class="product-item-inner actions clearfix">
                                        <div class="product product-item-actions show-box" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary actions-cart" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart">
                                                                <span><?php echo __('Add to Cart') ?>
                                                                </span>
                                                            </button>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_product->getIsSalable()) : ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <div data-role="add-to-links" class="actions-secondary add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php if ($showWishlist || $showCompare) : ?>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) : ?>
                                                        <a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                                            <span><?= $block->escapeHtml(__('Wish list')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($showCompare) :
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                        <a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                            <span><?= $block->escapeHtml(__('Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product details product-item-details products-textlink">

                            <?php
                            $categoryIds = $_product->getCategoryIds();
                            $categoryId  = count($categoryIds) ? current($categoryIds) : 0;
                            $category    = $categoryId ? $this->getCategory($categoryId) : '';
                            echo $category ? '<a class="category_name" href="' . $category->getUrl() . '">' . $category->getName() . '</a>' : '';
                            ?>
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h3 class="product-name product-item-name">
                                <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </h3>
                            <?php if ($templateType) {
                                $rating = $block->getReviewsSummaryHtml($_product, $templateType);
                                if ($rating) {
                                    echo $rating;
                                } else {
                            ?>
                                    <div class="product-reviews-summary short">
                                        <div class="rating-summary">
                                            <div class="rating-result" title="0%">
                                                <span style="width:0%"><span>0%</span></span>
                                            </div>
                                        </div>
                                        <div class="reviews-actions">
                                            <a class="action view" tabindex="0">0 &nbsp;<span>Reviews</span></a>
                                        </div>
                                    </div>
                            <?php }
                            } ?>
                            <div class="price-percent">
                                <?php echo $block->getProductPrice($_product) ?>
                                <?php
                                $SpecialPrice = $_product->getPriceInfo()->getPrice('special_price')->getValue();
                                if ($SpecialPrice) {
                                    $regular_price = $_product->getPriceInfo()->getPrice('regular_price')->getValue();
                                    $finalPriceAmt = $_product->getPriceInfo()->getPrice('final_price')->getValue();
                                    if ($finalPriceAmt > 0 && $regular_price > 0) {
                                        $_savePercent = 100 - round(($finalPriceAmt / $regular_price) * 100);
                                        if ($_savePercent > 0) {
                                ?>
                                            <div class="save-percent">
                                                <span><?php echo __('-') . $_savePercent . __('%'); ?></span>
                                            </div>
                                <?php
                                        }
                                    }
                                }
                                ?>
                            </div>
                            <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
                        </div>
                    </div>
                    <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
</script>
        <?php endif; ?>
    <?php endif; ?>
</div>