<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\RewardPoints\Block\Product\View\Discount */
$canShow = true;
if (!$block->isAjax()): ?>
    <?php $canShow = false ?>
    <div data-aw-reward-points-block-name="<?php /* @noEscape */ echo $block->getNameInLayout() ?>"></div>
<?php endif; ?>

<?php if ($canShow && $block->isDisplayBlock() && $block->getAvailablePoints() > 0) : ?>
    <div class="product-reward-points-discount">
        <?php /* @noEscape */ echo __('You have <strong>%1</strong> %2 which gives <strong>%3</strong> discount. You can apply your %2 on checkout.',
            $block->getAvailablePoints(),
            $block->getLabelNameRewardPoints(),
            $block->getFormattedAvailableAmount());
        ?>
    </div>
<?php endif; ?>
