<?php

/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>
<?php
$_imageHelper = $this->helper('Magiccart\Alothemes\Helper\Image');
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()) return ?>
<div class="widget block-recent-posts blog-slider" data-bind="scope: 'recent-posts'">
    <div class="block-title">
        <h3 class="title"><?php echo __($this->getTitle()) ?></h3>
        <p class="sub-title"><?php echo $this->getSubtitle(); ?></p>
    </div>
    <div class="block-content magicblog magicslider autoplay" <?php foreach ($this->getFrontendCfg() as $opt) : ?> data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>' <?php endforeach; ?>>
        <?php foreach ($_postCollection as $_post) { ?>
            <?php $_postUrl = $_post->getPostUrl(); ?>
            <?php $_postName = $block->escapeHtml($_post->getTitle()) ?>
            <div class="item">
                <div class="post-description">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        
                        <div class="post-ftimg-hld blog-image al-style-2 image-container">
                            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img width="340" height="270" src="<?php /* @escapeNotVerified */ echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                            </a>
                        </div>
                    <?php } ?>
                    <div class="post-item-detail">
                        <div class="post-header">
                            <div class="post-title-holder clearfix">
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <div class="post-categories">
                                        <?php $count = 0; ?>
                                        <?php $n = 0;
                                        foreach ($_post->getParentCategories() as $ct) {
                                            $n++; ?>
                                            <?php
                                            if ($count >= 1)
                                                break;
                                            $count++;
                                            ?>
                                            <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                <h3 class="post-title">
                                    <a class="post-item-link" href="<?php echo $_post->getPostUrl() ?>">
                                        <?php echo $_postName ?>
                                    </a>
                                </h3>
                                <div class="post-text-hld shortcontent-text clearfix">
                                    <?php echo $block->getShorContent($_post) ?>
                                </div>

                            </div>
                        </div>
                        <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                            <?php echo __('Read more') ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>