<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <div class="control">
        <input placeholder="<?= $block->escapeHtml(__('Phone number')) ?>" type="tel" name="telephone" id="telephone" value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= $block->escapeHtmlAttr(
                                                                                                                                                                                                        $block->getAttributeValidationClass('telephone')
                                                                                                                                                                                                    ) ?>">
    </div>
</div>