<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<tr class="item-info-custom">
    <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
        <?php if ($block->hasProductUrl()) : ?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>" title="<?php echo $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
            <?php else : ?>
                <span class="product-item-photo">
                <?php endif; ?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()) : ?>
            </a>
        <?php else : ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) : ?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else : ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) : ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else : ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()) : ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>">
                        <div><?php echo $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) : ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
            <div class="mobile_view_cart"> 
             <?php if ($canApplyMsrp) : ?>
        <div class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo ($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId; ?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                    <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                </a>
            </span>
               </div>
    <?php else : ?>
         <div class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php echo $block->getUnitPriceHtml($_item); ?>
       </div>
    <?php endif; ?>

     <div class="col qty mobile_cart" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty custom-qty clearfix">
                    <div class="cart_page_qty">
                    <button  type="button" class="alo_qty alo_qty_dec reduced ">
                            <svg width="13" height="12" viewBox="0 0 13 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M2.25586 5.99994H10.7459" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </button>
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           data-role="cart-item-qty"/>
                    <button  type="button" class="alo_qty alo_qty_inc increase">
                            <svg width="13" height="12" viewBox="0 0 13 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M2.25391 5.99945L10.7442 5.99945" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                              <path d="M6.5 10.2447L6.5 1.75433" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                    </button>
                    </div>     
                </div>
            </div>
        </div>
        <div class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php if ($canApplyMsrp) : ?>
            <span class="cart msrp subtotal">--</span>
        <?php else : ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
         <div class="col item-actions" >
        <div class="actions-toolbar">
            <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
        </div>
        </div>
    </div>

            </div>
             
        </div>
    </td>

    <?php if ($canApplyMsrp) : ?>
        <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo ($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId; ?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                    <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                </a>
            </span>
        </td>
    <?php else : ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php echo $block->getUnitPriceHtml($_item); ?>
        </td>
    <?php endif; ?>
    <td class="col qty dskremove" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty custom-qty clearfix">
                    <div class="cart_page_qty">
                    <button  type="button" class="alo_qty alo_qty_dec reduced ">
                            <svg width="13" height="12" viewBox="0 0 13 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M2.25586 5.99994H10.7459" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </button>
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           data-role="cart-item-qty"/>
                    <button  type="button" class="alo_qty alo_qty_inc increase">
                            <svg width="13" height="12" viewBox="0 0 13 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M2.25391 5.99945L10.7442 5.99945" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                              <path d="M6.5 10.2447L6.5 1.75433" stroke="#535865" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                    </button>
                    </div>     
                </div>
            </div>
        </td>

    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php if ($canApplyMsrp) : ?>
            <span class="cart msrp subtotal">--</span>
        <?php else : ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
    </td>
    <td class="col item-actions" colspan="100">
        <div class="actions-toolbar">
            <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
        </div>
    </td>
</tr>


<script type="text/javascript">


    // JavaScript code to remove the div for mobile devices
function removeDivOnMobile() {
    var divElement = document.querySelector('.dskremove'); // Replace '.example' with your div's class or identifier
    if (divElement && window.innerWidth <= 767) { // Adjust the threshold width as needed
        divElement.parentNode.removeChild(divElement);
    }
}

// Call the function when the window is resized
window.addEventListener('resize', removeDivOnMobile);

// Call the function once on page load
removeDivOnMobile();
</script>
