<?php
/**
 * Magedelight
 * Copyright (C) 2022 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2022 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */
  
$id = $block->getRequest()->getParam('entity_id');
$sms = $block->getSMSProfileDetailsById($id);
echo '<table width="100%" border="1">';
foreach ($sms->getData() as $key => $value) {
     echo "<tr>";
     echo '<td class = "profilefieldname" >'.$key.'</td>';
     echo '<td>'.$value.'</td>';
     echo "</tr>";
}
echo '</table>';
?>

<style type="text/css">
     th, td {
          padding: 15px;
     }
     table, th, td {
          border-collapse: collapse;
     }
     .profilefieldname { text-transform: capitalize; }
</style>