<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoReport
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * @var $block Bss\SeoReport\Block\Adminhtml\CrawlSelected
 */
?>
<div class="seo_report_header_crawl">
    <div class="seo_report_button" id="bss_seo_report_start_crawl">
        <?= /* @noEscape */ __($block->getButtonText()) ?>
    </div>
    <a href="<?= /* @noEscape */ $block->getDashboardLink() ?>">
        <div class="seo_report_button right"><?= /* @noEscape */ __($block->getBackButtonText()) ?></div>
    </a>
</div>
<div class="seo_report_body_crawl">
    <div class="seo_report_process_crawl">
        <div class="seo_report_percent_crawl" id="seo_report_percent_crawl"></div>
    </div>
    <div class="seo_report_show_crawl">
        <div class="seo_report_show_crawl_child" id="seo_report_show_crawl_child">
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_SeoReport/js/crawl": <?= /* @noEscape */ $block->getJsonData(); ?>
        }
    }
</script>
