<?php
/**
 * 
 * @category: Magepow
 * @Copyright (c) 2014 Magepow  (<https://www.magepow.com>)
 * @authors: Magepow (<magepow<support@magepow.com>>)
 * @date:    2021-04-27 16:26:18
 * @license: <http://www.magepow.com/license-agreement>
 * @github: <https://github.com/magepow> 
 */
 /** @var \Magepow\AjaxWishlist\Block\Form\Login $block */
?>
<?php 
    $helper = $this->helper('Magepow\AjaxWishlist\Helper\Data');
    $imgWishlist = $helper->getConfigModule('general/image');
    $urlMedia = $helper->getBaseUrlMedia();
?>
<?php if (!$block->customerIsAlreadyLoggedIn()): ?>

    <div id="customer-popup-login" class="customer-wishlist-login-custom customer-popup-login _disabled">
        <div class="block block-customer-login custom-login-whishlist-popup-main">
            <div class="block-content" aria-labelledby="block-customer-popup-login-heading">

                <h3 style="color:red;" class="error-msg-custom-wishlist"><?php echo __("You must login or register to add items to your wishlist."); ?></h3>
                <div class="form form-login">
                   <div class="actions-toolbar">
                            <div class="primary"><a class="customer-login-btn" href="<?php echo $this->getUrl('customer/account/login'); ?>" class="action login primary" name="send" id="send2-login"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></a></div>
                            <?php if ($block->getRegistration()->isAllowed()): ?>
                            <div class="secondary">
                                <p class="heading-second"><?php echo __('Don’t have an account?'); ?></p>
                                <a class="customer-create-btn action remind" href="<?php /* @escapeNotVerified */ echo $block->getCustomerRegistrationUrl() ?>" id="customer-popup-registration"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#customer-popup-login": {
                    "Magepow_AjaxWishlist/js/action/customer-authentication-popup": {
                        "innerWidth": "400"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
