<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/** @var $block \Magefan\Blog\Block\Social\AddThis */
?>
<?php /*
<script type="text/javascript">
    var addthis_config = {
        "ui_language": '<?= $block->escapeHtml($block->getAddThisLanguage()) ?>',
        "data_track_clickback":false
    }
</script>
<script type="text/javascript" async
        src="<?= '/' . '/' ?>s7.addthis.com/js/300/addthis_widget.js#pubid=<?= $block->escapeUrl($block->getAddThisPubId()) ?>"></script>
*/ ?>

<script>
    function mfShareWindowOpen(url, type) {
        function reverse(s){
            return s.split("").reverse().join("");
        }

        var u;
        switch (type) {
            case 'facebook':
                u = reverse('<?= strrev('https://www.facebook.com/sharer/sharer.php?u=') ?>') + url;
                break;
            case 'youtube':
                u = reverse('<?= strrev('http://youtube.com/share?url=') ?>') + url;
                break;
            case 'instagram':
                u = reverse('<?= strrev('http://instagram.com/share?url=') ?>') + url;
                break;
            case 'tiktok':
                u = reverse('<?= strrev('http://tiktok.com/share?url=') ?>') + url;
                break;
            case 'snapchat':
                u = reverse('<?= strrev('http://snapchat.com/share?url=') ?>') + url;
                break;
            case 'whatsapp':
                u = reverse('<?= strrev('https://web.whatsapp.com/send?text=') ?>') + url;
                break;           
            case 'twitter':
                u =reverse('<?= strrev('http://twitter.com/share?url=') ?>') + url;
                break;
        }
        if (u) {
            window.open (u, null, "width=600,height=400");
        }
    }
</script>
