<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>
<?php if($this->getRequest()->getFullActionName() == 'cms_index_index'): ?>
    <h1 class="logo">
	<?php else: ?> 
    <div class="logo">
<?php endif; ?>
<a  class="logo-link" href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
    />
</a>
<?php if($this->getRequest()->getFullActionName() == 'cms_index_index'): ?>
    </h1>
<?php else: ?> 
    </div>
<?php endif; ?>
