<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoToolbar
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
/**
 * SEO Toolbar template
 *
 * @var $block \Bss\SeoToolbar\Block\SeoToolbar
 */
?>

<?php
$ajaxUrl = $block->getAjaxUrl();
$entityObject = $block->getEntityObject();

$dataJson = [
    "ajaxUrl" => $ajaxUrl,
    "entityId" => $entityObject['entity_id'],
    "entityType" => $entityObject['entity_type'],
    "logoUrl" => $block->getViewFileUrl('Bss_SeoToolbar::images/logo_bss.svg')
];
$dataJsonEncode = $block->getDataHelper()->jsonEncode($dataJson);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_SeoToolbar/js/seo_toolbar": <?= /* @noEscape */ $dataJsonEncode; ?>
        }
    }
</script>

<div id="bss_seo_toolbar">

</div>
