<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoToolbar
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Seo Toolbar Generate Button
 * @var $block \Bss\SeoToolbar\Block\System\Config\Check
 */
?>
<?php
$baseUrl = $block->getBaseUrl();
$tokenCode = $block->getTokenCode();
$urlToCheck = $baseUrl . '?token=' . $tokenCode;
?>
<a href="<?= /* @noEscape */ $urlToCheck; ?>" target="_blank">
    <?= $block->getButtonHtml() ?>
</a>
