<?php
use Aheadworks\RewardPoints\Block\Customer\Subscribe;
use Magento\Framework\Escaper;

/** @var Subscribe $block */
/** @var Escaper $escaper */
?>
<?php if ($block->canShow()): ?>
    <legend class="legend">
        <span><?php /* @noEscape */ echo __($block->getLabelNameRewardPoints()) ?></span>
    </legend>
    <br>
    <div class="field choice">
        <input type="checkbox"
               name="aw_rewardpoints_is_balance_update_subscribed"
               id="aw_rewardpoints_balance_update_subscription"
               value="1"
               title="<?php echo $escaper->escapeHtml(__('Subscribe to balance update notifications')) ?>"
               <?php if ($block->isBalanceUpdateSubscribed()): ?> checked="checked"<?php endif; ?>
               class="checkbox">
        <label for="aw_rewardpoints_balance_update_subscription" class="label">
            <span><?php echo $escaper->escapeHtml(__('Subscribe to balance update notifications')) ?></span>
        </label>
    </div>
    <div class="field choice">
        <input type="checkbox"
               name="aw_rewardpoints_is_expiration_subscribed"
               id="aw_rewardpoints_is_expiration_subscribed"
               value="1"
               title="<?php echo $escaper->escapeHtml(__('Subscribe to points expiration reminders')) ?>"
               <?php if ($block->isExpirationSubscribed()): ?> checked="checked"<?php endif; ?>
               class="checkbox">
        <label for="aw_rewardpoints_is_expiration_subscribed" class="label">
            <span><?php echo $escaper->escapeHtml(__('Subscribe to points expiration reminders')) ?></span>
        </label>
    </div>
<?php endif; ?>
