<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_RichSnippets
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * General Block
 * @var $block Bss\RichSnippets\Block\Product\View
 */
?>
<?php
$helper = $block->getHelper();
$getEnableModule = $helper->getEnable();
$getEnable = $helper->getEnableForProduct();
$getEnableTwitter = $helper->getEnableForProductT();
$twitterUser = $helper->getTwitterUser();
$description = $block->getDescription();

?>
<?php if ($getEnableModule == '1'): ?>
	<?php
    if ($getEnable == '1'): ?>
        <meta property="og:type" content="og:product" />
        <meta property="og:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta property="og:image" content="<?php echo $block->escapeUrl(
            $block->getUrlImg($block->getProduct())); ?>" />
        <meta property="og:description" content="<?php echo $block->escapeHtml(
                $description); ?>" />
        <meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />

	<?php
    endif; ?>
	<?php
    if ($getEnableTwitter == '1'): ?>
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="<?php echo $block->escapeUrl($twitterUser); ?>" />
        <meta name="twitter:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta name="twitter:description" content="<?php echo $block->escapeHtml(
                $description); ?>" />
        <meta name="twitter:image" content="<?php echo $block->escapeUrl(
            $block->getUrlImg($block->getProduct())); ?>" />

	<?php
    endif; ?>
	<?php
    if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
        <meta property="product:price:amount" content="<?php /* @escapeNotVerified */ echo $priceAmount; ?>"/>
	    <?php echo $block->getChildHtml('meta.currency'); ?>
	<?php
    endif; ?>
    <?php
else: ?>
        <meta property="og:type" content="og:product" />
        <meta property="og:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta property="og:image" content="<?php echo $block->escapeUrl(
            $block->getUrlImg($block->getProduct())); ?>" />
        <meta property="og:description" content="<?php echo $block->escapeHtml(
                $block->getProduct()->getShortDescription()); ?>" />
        <meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />
        <?php
    if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
            <meta property="product:price:amount" content="<?php /* @escapeNotVerified */ echo $priceAmount; ?>"/>
            <?php echo $block->getChildHtml('meta.currency'); ?>
        <?php
    endif;?>
    <?php
endif;
