<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="contact-content">
    <div class="form-primary">
        <div class="row">
            <div class="col-xl-5 col-lg-5 col-md-12 col-12 form-primary-item">
                <div class="store-contact">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store-contact')->toHtml();?>
                </div>
            </div>
            <div class="col-xl-7 col-lg-7 col-md-12 col-12 form-primary-item">
                 <form class="form contact" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                    <div class="form-contact">
                         <fieldset class="fieldset">
                             <h3 class="block-title"><?php /* @escapeNotVerified */ echo __('Send us an message') ?></h3>
                            <div class="field info">
                                 <div class="field name required">
                                    <div class="control">
                                           <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Your Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Your name') ?>"/>
                                    </div>
                                 </div>
                                 <div class="field email required">
                                     <div class="control">
                                        <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Your Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Your email') ?>"/>
                                     </div>
                                 </div>
                            </div>
                            <div class="field comment required">
                                 <div class="control">
                                     <textarea rows="10" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Your Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Your question here...') ?>"></textarea>
                                </div>
                            </div>
                            <?php echo $block->getChildHtml('form.additional.info'); ?>
                             <div class="actions-toolbar">
                                <div class="primary">
                                    <input type="hidden" name="hideit" id="hideit" value="" />
                                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
                                    </button>
                                 </div>
                             </div>
                        </fieldset>
                    </div>
                </form>                    
            </div>
        </div>
    </div>
</div>

<!-- Messenger Plugin chat Code -->
<div id="fb-root"></div>

<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>