<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product information
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$proId = $currentProduct->getId();
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$currentProduct = $productRepository->getById($proId);
$categoryIds = $currentProduct->getCategoryIds();
$categories = $categoryCollection->create()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('entity_id', $categoryIds);

?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()) : ?>
    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>" class="action mailto friend">
        <!-- <i class="pe-7s-mail icons"></i> --><span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
    </a>
<?php endif; ?>
<div class="product-sku">
    <span class="lable">Sku:</span>&nbsp;<span class="sku"><?php echo $currentProduct->getSku(); ?></span>
</div>
<div class="categories-product-view">
    Categories:&nbsp;
    <?php
    $i = 0;
    foreach ($categories as $category) :
        if (++$i == 4) break;
    ?>
        <?php $cat = $category->getName()?>
        <a href="<?php echo $category->getUrl() ?>"><?php echo $cat ?></a>
        <span class="command"> , </span>
    <?php endforeach; ?>
</div>
<div class="delivery-return">
    <a class="delivery-return-text"><?php echo __('Delivery & Return') ?></a>
    <div id="delivery-return-popup" style="display: none;"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('delivery_and_return')->toHtml(); ?></div>
</div>
<div class="service-customers">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-customers')->toHtml(); ?>
</div>
<?php $slash2 = '//'; ?>
<div class="alo-social-links socials clearfix addit">

    <div class="custom-html">
        <h3 class="title-social"><?php /* @escapeNotVerified */ echo __('Share it:') ?></h3>
        <ul class="list-inline">
            <li class="facebook">
                <a class="trasition-all social-link facebook" title="<?php echo __('Share on Facebook') ?>" href="#" target="_blank" rel="nofollow" onclick="window.open('<?php echo $slash2 ?>www.facebook.com/sharer/sharer.php?u='+'<?php echo $_product->getProductUrl(); ?>&picture=<?php echo $_product->getImageUrl(); ?>');return false;"><em class="fa fa-facebook"><span class="hidden"><?php /* @escapeNotVerified */ echo __('facebook') ?></span></em>
                </a>
            </li>
            <li class="twitter">
                <a class="trasition-all social-link twitter" href="#" title="<?php echo __('Share on Twitter') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>twitter.com/share?text=<?php echo $_product->getName(); ?>&amp;url=<?php echo $_product->getProductUrl(); ?>');return false;"><em class="fa fa-twitter"><span class="hidden"><?php /* @escapeNotVerified */ echo __('twitter') ?></span></em>
                </a>
            </li>
            <li class="pinterest">
                <a class="trasition-all social-link pinterest" href="#" title="<?php echo __('Pin this') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>pinterest.com/pin/create/button/?url=<?php echo $_product->getProductUrl(); ?>&amp;media=http%3A%2F%2Fdemo.cactusthemes.com%2Fnewstube%2Fwp-content%2Fuploads%2F2015%2F06%2F014-Surf-woman.jpg&amp;description=<?php echo $_product->getName(); ?>');return false;"><em class="fa fa-pinterest"><span class="hidden"><?php /* @escapeNotVerified */ echo __('pinterest') ?></span></em>
                </a>
            </li>
            <li class="linkedin">
                <a class="trasition-all social-link linkedin" href="#" title="<?php echo __('Share on LinkedIn') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $_product->getProductUrl(); ?>&amp;title=<?php echo $_product->getName(); ?>');return false;"><em class="fa fa-linkedin"><span class="hidden"><?php /* @escapeNotVerified */ echo __('linkedin') ?></span></em>
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="view-full-page-details">
    <a href="<?php echo $_product->getProductUrl() ?>"><?php /* @escapeNotVerified */ echo __('View full details ') ?></a>
</div>