<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Product Feed for Magento 2
 */ /** @var \Amasty\Feed\Block\Adminhtml\System\Config\SuggestNotification $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->shouldShowNotification()): ?>
    <div>
        <p class="message message-notice">
            <?= $escaper->escapeHtml($block->getNotificationText()) ?>
            <a target="_blank" href="<?= $escaper->escapeUrl($block->getSuggestLink()) ?>">
                <?= $escaper->escapeHtml(__('here')) ?>
            </a>.
        </p>
    </div>
<?php endif;?>
