<?php
$brand = $block->getBrand();
if(!$brand) return;
$helper =  $this->_helper;
$image = $brand->getImage();
$description = $this->getDescription();
?>
<?php if($image) : ?>
<div class="brand-view">
    <div class="image">
        <img class="img-responsive" src="<?= $helper->getMediaUrl($image) ?>" alt="<?= $brand->getTitle(); ?>"/>
    </div>
    <?php endif; ?>
    <div class="detail">
        <?php echo $description ? '<div class="brand-description">' . $description . '</div>' : ''; ?>
    </div>
</div>
