<?php

/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Magefan\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<?php if ($block->magefanCommentsEnabled() && $_post->getCommentsCount()) { ?>
    <div class="item post-comments">
        <i class="mf-blog-icon mfbi-comments"></i>
        <span class="label">
            <?php if ($_post->getCommentsCount() == 1) :  ?>
                <?= $block->escapeHtml(__('Comment:')) ?>
            <?php else : ?>
                <?= $block->escapeHtml(__('Comments:')) ?>
            <?php endif; ?>
        </span>
        <a title="<?= $block->escapeHtml($_post->getTitle()) ?>" href="<?= $block->escapeUrl($_post->getPostUrl()) ?>#post-comments"><?= $block->escapeHtml($_post->getCommentsCount()) ?></a>
    </div>
<?php } ?>
<!-- <?php if ($_tagsCount = $_post->getTagsCount()) { ?>
    <div class="item post-tags">
        <div class="mf-blog-icon mfbi-tags"></div>
        <span class="label"><?= $block->escapeHtml(__('Tags:')) ?></span>
        <?php $n = 0; ?>
        <?php foreach ($_post->getRelatedTags() as $tag) { ?>
            <?php $n++; ?>
            <a title="<?= $block->escapeHtml($tag->getTitle()) ?>" href="<?= $block->escapeUrl($tag->getTagUrl()) ?>"><?= $block->escapeHtml($tag->getTitle()) ?></a><?= ($n != $_tagsCount) ? ',' : '' ?>
        <?php } ?>
    </div>
<?php } ?> -->

<?php if ($block->viewsCountEnabled()) { ?>
    <?php if ($viewsCount = $_post->getViewsCount()) { ?>
        <div class="item post-views">
            <i class="mf-blog-icon mfbi-views"></i>
            <span class="label"><?= $block->escapeHtml(__('Views:')) ?></span>
            <span class="value">
                <?= $block->escapeHtml($viewsCount) ?>
            </span>
        </div>
    <?php } ?>
<?php } ?>