<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" data-bind="scope: 'minicart_content'">
        <span class="pe-7s-shopbag">
            <svg width="24" height="24" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.9126 9.82999C6.9126 9.82999 8.9126 3.82999 11.5793 3.82999C14.1828 3.82999 16.2459 9.83004 16.2459 9.83004M2.9126 12.4967L2.33018 10.1634H20.9126C20.9126 10.1634 19.5793 16.1634 18.9126 18.1634C18.6157 19.0539 17.8513 19.23 16.9126 19.23C13.5793 19.2301 12.3708 19.23 9.43105 19.23C7.7354 19.1748 7 19.5 5 19C4.5 19 4.17075 17.683 4 17C3.5 15 2.9126 12.4967 2.9126 12.4967Z" stroke="#C18F2C" stroke-width="1.5"></path></svg>
            <span class="text"><?php echo __('Cart') ?></span>
            <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                <span class="counter-label">
                    <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') -->
                    <!-- /ko -->
                    <!-- ko i18n: 'items' -->
                    <!-- /ko -->
                    <!-- /ko -->
                </span>
            </span>
        </span>
        <span class="minicart-text">
            <span class="text cart-title"><?php /* @escapeNotVerified */ echo __('Cart'); ?></span>
            <span data-bind="html: getCartParam('subtotal')"></span>
        </span>
    </a>
    <div class="block block-minicart" data-role="dropdownDialog" data-mage-init='{"dropdownDialog":{
            "appendTo":"[data-block=minicart]",
            "triggerTarget":".showcart",
            "timeout": "2000",
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":[]}}'>
    <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() -->
                <!-- /ko -->
            </div>
            <?php endif ?>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo $block->getSerializedConfig(); ?>;
    </script>
    <script type="text/x-magento-init">
        {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>