<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoReport
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Seo Toolbar Generate Button
 * @var $block Bss\SeoReport\Block\Adminhtml\SeoReport\PageType\Product
 */
?>
<?php
$helperData = $block->getDataHelper();
$statusEnable = $helperData->getEnableModule();
?>
<?php if ((int)$statusEnable): ?>
    <div class="bss_seo_report google_search_console_view">
        <div class="bss_seo_report_left">
            <label>
                <span data-config-scope="[STORE VIEW]"><?php echo __("Google Search Console"); ?></span>
            </label>
        </div>
        <div class="bss_seo_report_right_audit" id="google_search_console_view">
        </div>
    </div>
<?php endif; ?>