<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoReport
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Seo Toolbar Generate Button
 * @var $block Bss\SeoReport\Block\Adminhtml\SeoReport\PageType\Product
 */
?>
<?php
    $descriptionInfo = $block->getDescriptionInfo();
    $colorDescription = $descriptionInfo['color'];
    $percentDescription = $descriptionInfo['percent'];
?>
<?php
$helperData = $block->getDataHelper();
$statusEnable = $helperData->getEnableModule();
?>
<?php if ((int)$statusEnable): ?>
    <div class="bss_seo_report meta_description_report">
        <div class="bss_seo_report_right" id="meta_description_report">
            <div class="meta_report_item <?php echo $colorDescription; ?>" style="width: <?php echo $percentDescription; ?>%">
            </div>
        </div>
    </div>
<?php endif; ?>