<?php
namespace Galaxyweblinks\Liltshipping\Setup;

use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\InstallDataInterface;

class InstallData implements InstallDataInterface
{
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();

        $tableName = $setup->getTable('lilt_shipping_city_table');

       
$data = [
    ['city' => 'Sabya', 'transcity'=> 'صبيا', 'selected' => '0'],
    ['city' => 'Bisha', 'transcity'=> 'بيشة', 'selected' => '0'],
    ['city' => 'Namas', 'transcity'=> 'ناماس', 'selected' => '0'],
    ['city' => 'Kharj', 'transcity'=> 'الخرج', 'selected' => '0'],
    ['city' => 'Hawtat Bani Tamim', 'transcity'=> 'حوطة بني تميم', 'selected' => '0'],
    ['city' => 'Wadi El Dwaser', 'transcity'=> 'وادي الدواسر', 'selected' => '0'],
    ['city' => 'Harad', 'transcity'=> 'حرض', 'selected' => '0'],
    ['city' => 'Rafha', 'transcity'=> 'رفحاء', 'selected' => '0'],
    ['city' => 'Dereiyeh', 'transcity'=> 'الدرعية', 'selected' => '0'],
    ['city' => 'Hareeq', 'transcity'=> 'حريق',  'selected' => '0'],
    ['city' => 'Hotat Sudair', 'transcity'=> 'حوطة سدير',  'selected' => '0'],
    ['city' => 'Quweiieh', 'transcity'=> 'القويعية',  'selected' => '0'],
    ['city' => 'Sajir', 'transcity'=> 'ساجر',  'selected' => '0'],
    ['city' => 'Deraab', 'transcity'=> 'ديراب',  'selected' => '0'],
    ['city' => 'Horaimal', 'transcity'=> 'هورايمال',  'selected' => '0'],
    ['city' => 'Salbookh', 'transcity'=> 'صلبوخ',  'selected' => '0'],
    ['city' => 'Dhurma', 'transcity'=> 'دورما',  'selected' => '0'],
    ['city' => 'Aflaj' , 'transcity'=> 'الأفلاج',  'selected' => '0'],
    ['city' => 'Khulais', 'transcity'=> 'خليص',  'selected' => '0'],
    ['city' => 'Tebrak', 'transcity'=> 'تبرق',  'selected' => '0'],
    ['city' => 'Rwaydah', 'transcity'=> 'الرويضة',  'selected' => '0'],
    ['city' => 'Afif', 'transcity'=> 'عفيف',  'selected' => '0'],
    ['city' => 'Sulaiyl', 'transcity'=> 'السليل',  'selected' => '0'],
    ['city' => 'Thumair', 'transcity'=> 'ثمير',  'selected' => '0'],
    ['city' => 'Remah', 'transcity'=> 'رماح',  'selected' => '0'],
    ['city' => 'Jalajel', 'transcity'=> 'Jalajel',  'selected' => '0'],
    ['city' => 'Artawiah', 'transcity'=> 'ارطاوية',  'selected' => '0'],
    ['city' => 'AlRass' , 'transcity'=> 'الرس',  'selected' => '0'],
    ['city' => 'Bukeiriah' , 'transcity'=> 'البكيرية',  'selected' => '0'],
    ['city' => 'Badaya' , 'transcity'=> 'بدايا',  'selected' => '0'],
    ['city' => 'Zulfi', 'transcity'=> 'الزلفي',  'selected' => '0'],
    ['city' => 'Haqil', 'transcity'=> 'حقل',  'selected' => '0'],
    ['city' => 'Oula', 'transcity'=> 'أولا',  'selected' => '0'],
    ['city' => 'Al Bada', 'transcity'=> 'البدع',  'selected' => '0'],
    ['city' => 'Jafar', 'transcity'=> 'جعفر',  'selected' => '0'],
    ['city' => 'Alghat', 'transcity'=> 'الغات',  'selected' => '0'],
    ['city' => 'Nabiya' , 'transcity'=> 'نبية',  'selected' => '0'],
    ['city' => 'Udhaliyah', 'transcity'=> 'العذلية',  'selected' => '0'],
    ['city' => 'Sakaka', 'transcity'=> 'سكاكا',  'selected' => '0'],
    ['city' => 'Arar' , 'transcity'=> 'عرعر',  'selected' => '0'],
    ['city' => 'Domat Al Jandal' , 'transcity'=> 'دومة الجندل',  'selected' => '0'],
    ['city' => 'Turaif' , 'transcity'=> 'طريف',  'selected' => '0'],
    ['city' =>  'Qurayat', 'transcity'=> 'قريات',  'selected' => '0'],
    ['city' =>  'Tabrjal' , 'transcity'=> 'طبرجل',  'selected' => '0'],
    ['city' =>  'Duba' , 'transcity'=> 'ضباء',  'selected' => '0'],
    ['city' =>   'Majarda' , 'transcity'=> 'ماجاردا',  'selected' => '0'],
    ['city' =>  'Uqlat Al Suqur' , 'transcity'=> 'عقلة الصقور',  'selected' => '0'],
    ['city' =>   'Riyadh Al Khabra' , 'transcity'=> 'رياض الخبراء',  'selected' => '0'],
    ['city' =>   'Riyadh' , 'transcity'=> 'الرياض',  'selected' => '0'],
    ['city' =>   'Wajeh' , 'transcity'=> 'وجيه',  'selected' => '0'],
    ['city' =>  'Midinhab', 'transcity'=> 'مدينهاب',  'selected' => '0'],
    ['city' =>   'Halat Ammar' , 'transcity'=> 'حلات عمار',  'selected' => '0'],
    ['city' =>  'Jouf', 'transcity'=> 'الجوف',  'selected' => '0'],
    ['city' =>  'Assiyah', 'transcity'=> 'آسيا',  'selected' => '0'],
    ['city' =>   'Hadeethah', 'transcity'=> 'حديثة',  'selected' => '0'],
    ['city' =>   'Birk' , 'transcity'=> 'بيرك',  'selected' => '0'],
    ['city' =>   'Mikhwa', 'transcity'=> 'ميخوا',  'selected' => '0'],
    ['city' =>  'Sarat Obeida' , 'transcity'=> 'سراة عبيدة',  'selected' => '0'],
    ['city' =>   'Rejal Almaa', 'transcity'=> 'رجال ألما',  'selected' => '0'],
    ['city' =>  'Mandak', 'transcity'=> 'مانداك',  'selected' => '0'],
    ['city' =>   'Abha' , 'transcity'=> 'أبها',  'selected' => '0'],
    ['city' =>   'Darb' , 'transcity'=> 'درب',  'selected' => '0'],
    ['city' =>   'Ash Shuqaiq' , 'transcity'=> 'آل الشقيق',  'selected' => '0'],
    ['city' =>   'Sharourah', 'transcity'=> 'شرورة',  'selected' => '0'],
    ['city' =>  'Tanuma' , 'transcity'=> 'تنومة',  'selected' => '0'],
    ['city' =>  'THUWAL', 'transcity'=> 'ثول',  'selected' => '0'],
    ['city' =>  'Rania' , 'transcity'=> 'رانيا',  'selected' => '0'],
    ['city' =>  'Muthaleif' , 'transcity'=> 'مكلف',  'selected' => '0'],
    ['city' =>  'Abu Areish', 'transcity'=> 'ابو عريش',  'selected' => '0'],
    ['city' =>  'Dhahran Al Janoob', 'transcity'=> 'ظهران الجنوب',  'selected' => '0'],
    ['city' =>  'Aqiq' , 'transcity'=> 'عقيق',  'selected' => '0'],
    ['city' =>  'Wadeien' , 'transcity'=> 'واديين',  'selected' => '0'],
    ['city' =>   'Harjah', 'transcity'=> 'حرجة',  'selected' => '0'],
    ['city' =>   'Najran', 'transcity'=> 'نجران',  'selected' => '0'],
    ['city' =>   'Baha', 'transcity'=> 'بهاء',  'selected' => '0'],
    ['city' =>  'BilJurashi', 'transcity'=> 'بالجرشي',  'selected' => '0'],
    ['city' =>  'Sabt El Alaya', 'transcity'=> 'سبت العلايا',  'selected' => '0'],
    ['city' =>  'Khodaria', 'transcity'=> 'خضرية',  'selected' => '0'],
    ['city' =>  'Yanbu', 'transcity'=> 'ينبع',  'selected' => '0'],
    ['city' =>  'Rabigh', 'transcity'=> 'رابغ',  'selected' => '0'],
    ['city' =>  'Umluj', 'transcity'=> 'أملج',  'selected' => '0'],
    ['city' =>  'Bish', 'transcity'=> 'بيش',  'selected' => '0'],
    ['city' =>   'Laith' , 'transcity'=> 'ليث',  'selected' => '0'],
    ['city' =>  'Atawleh' , 'transcity'=> 'العطاولة',  'selected' => '0'],
    ['city' =>  'Ahad Masarha', 'transcity'=> 'أحد مسرحها',  'selected' => '0'],
    ['city' =>  'Ahad Rufaidah' , 'transcity'=> 'عهد رفيدة',  'selected' => '0'],
    ['city' =>   'Samtah', 'transcity'=> 'صامطة',  'selected' => '0'],
    ['city' =>   'Tatleeth', 'transcity'=> 'تاتليث',  'selected' => '0'],
    ['city' => 'Thabya', 'transcity'=> 'ذبيحه',  'selected' => '0'],
    ['city' => 'Qariya Al Olaya', 'transcity'=> 'قرية العليا',  'selected' => '0'],
    ['city' => 'Al Hassa' , 'transcity'=> 'الحسا',  'selected' => '0'],
    ['city' => 'Qaysoomah', 'transcity'=> 'القيصومة',  'selected' => '0'],
    ['city' => 'Seihat' , 'transcity'=> 'سيهات',  'selected' => '0'],
    ['city' => 'Ras Al Kheir', 'transcity'=> 'رأس الخير',  'selected' => '0'],
    ['city' => 'Safanyah', 'transcity'=> 'السفانية',  'selected' => '0'],
    ['city' => 'Qassim', 'transcity'=> 'القصيم',  'selected' => '0'],
    ['city' =>   'Turaib', 'transcity'=> 'طريب',  'selected' => '0'],
    ['city' =>   'Farasan' , 'transcity'=> 'فرسان',  'selected' => '0'],
    ['city' =>    'Hawea/Taif', 'transcity'=> 'الحوا / الطائف',  'selected' => '0'],
    ['city' =>    'Subheka', 'transcity'=> 'سوبهيكا',  'selected' => '0'],
    ['city' =>   'Khaibar', 'transcity'=> 'خيبر',  'selected' => '0'],
    ['city' =>   'Turba', 'transcity'=> 'توربا',  'selected' => '0'],
    ['city' =>   'Jumum' , 'transcity'=> 'جوموم',  'selected' => '0'],
    ['city' =>    'Khurma', 'transcity'=> 'خورما',  'selected' => '0'],
    ['city' =>  'Shoaiba' , 'transcity'=> 'الشعيبة',  'selected' => '0'],
    ['city' =>   'Bader', 'transcity'=> 'بدر',  'selected' => '0'],
    ['city' =>   'Mahad Al Dahab' , 'transcity'=> 'مهاد الذهب',  'selected' => '0'],
    ['city' =>  'Hinakeya' , 'transcity'=> 'هيناكيا',  'selected' => '0'],
    ['city' => 'Noweirieh' , 'transcity'=> 'النويرية',  'selected' => '0'],
    ['city' => 'Hofuf', 'transcity'=> 'الهفوف',  'selected' => '0'],
    ['city' => 'Qatif' , 'transcity'=> 'القطيف',  'selected' => '0'],
    ['city' => 'Salwa'  , 'transcity'=> 'سلوى',  'selected' => '0'],
    ['city' => 'Ras Tanura' , 'transcity'=> 'رأس تنورة',  'selected' => '0'],
    ['city' => 'Jaaraneh'  , 'transcity'=> 'جعرانة',  'selected' => '0'],
    ['city' =>  'Batha' , 'transcity'=> 'البطحاء',  'selected' => '0'], 
    ];

        $setup->getConnection()->insertMultiple($tableName, $data);

        $setup->endSetup();
    }
}
