<?php

/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
    <div class="post-list-wrapper blog-widget-recent">
        <div class="post-title">
            <h3 class="title"><?= $block->escapeHtml($block->getTitle()) ?></h3>
        </div>
        <ul class="post-list clearfix">
            <?php foreach ($_postCollection as $_post) { ?>
                <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
                ?>
                <li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
                    <div class="post-content">
                        <div class="post-image-holder">
                            <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                            <?php if ($featuredImage) { ?>
                                <?php
                                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                if (!$featuredImgAlt) {
                                    $featuredImgAlt = $_postName;
                                }
                                ?>
                                <div class="post-ftimg-hld">
                                    <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                        <img src="<?= $block->escapeHtml($featuredImage) ?>" alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                                    </a>
                                </div>
                            <?php } ?>
                        </div>

                        <div class="post-detail-holder clearfix">
                            <div class="post-title">
                                <a class="post-item-link" href="<?= /*@noEscape*/ $_postUrl ?>">
                                    <?= /*@noEscape*/ $_postName ?>
                                </a>
                            </div>
                            <div class="post-more-info">
                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                <span class="publish-date">
                                    <span class="month"><?php echo $_post->getPublishDate('M') ?></span>
                                    <span class="date"><?php echo $_post->getPublishDate('d') ?></span>,
                                    <span class="year"><?php echo $_post->getPublishDate('Y') ?></span>
                                </span>
                            <?php } ?>
                                <?php if ($_post->getCommentsCount()) : ?>
                                    <div class="item post-comments">
                                        <span title="<?= $block->escapeHtml($_post->getTitle()) ?>" href="<?= $block->escapeUrl($_post->getPostUrl()) ?>#post-comments"><?= $block->escapeHtml($_post->getCommentsCount()) ?></span>
                                        <span class="label">
                                            <?php if ($_post->getCommentsCount() == 1) :  ?>
                                                <?= $block->escapeHtml(__('Comment')) ?>
                                            <?php else : ?>
                                                <?= $block->escapeHtml(__('Comments')) ?>
                                            <?php endif; ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>