<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$nextPage = ($_productCollection->getCurPage() == $_productCollection->getLastPageNumber()) ? 0 : $_productCollection->getCurPage(+1);
?>
<div class="mage-magictabs mc-<?php echo $this->escapeHtml($this->getTypeFilter()); ?>" data-next-page="<?php /* @escapeNotVerified */ echo $nextPage ?>">
    <?php if (!$_productCollection->count()) : ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php else : ?>
        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <?php
        $config     = $this->getWidgetCfg();
        $timer          = $config['timer']    ?? '';
        $showCart       = $config['cart']     ?? '';
        $showCompare    = $config['compare']  ?? '';
        $showWishlist   = $config['wishlist'] ?? '';
        $showReview     = $config['review']   ?? '';
        $swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Magiccart_Magicproduct::product/listing/renderer.phtml');
        ?>
         <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info per-product" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="images-container">
                        <?php 
                            $product_label = $_aloHelper->getLabels($_product); 
                            echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : ''; 
                        ?>
                        <div class="product-hover">
                            <?php //echo $_aloHelper->getTimer($_product); ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                             <!-- <div class="link-view">
                                <button type="button" class="quickview <?php echo $_product->getTypeId() ?>"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><i class="fa fa-eye icons"></i><?php echo __('Quick View')?></span>
                                </button>
                             </div> -->
                        </div>
                        <div class="product details new-home product-item-details products-textlink clearfix">
                            <div class="custom-review-section-related-blk">
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                            </div>
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h2 class="product-name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </h2>
                            <?php echo $block->getProductPrice($_product) ?>  
                        </div>
                        <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product product-item-actions new-home show-box"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary actions-cart"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                
                                                <form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary button btn-cart">
                                                            <?php /* @escapeNotVerified */ echo __('Add to Cart') ?> 
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                           <?php if ($showCompare):
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#"
                                                   class="action tocompare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <i class="icon fa fa-exchange"></i><?php echo __('Add to Compare') ?>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   class="action towishlist1"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                     <div class="custom-wishlist-image"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                                                          <path d="M9.465 15.6075C9.21 15.6975 8.79 15.6975 8.535 15.6075C6.36 14.865 1.5 11.7675 1.5 6.51751C1.5 4.20001 3.3675 2.32501 5.67 2.32501C7.035 2.32501 8.2425 2.98501 9 4.00501C9.7575 2.98501 10.9725 2.32501 12.33 2.32501C14.6325 2.32501 16.5 4.20001 16.5 6.51751C16.5 11.7675 11.64 14.865 9.465 15.6075Z" stroke="#7E828B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                                        </svg></div> 
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
</script>
        <?php endif; ?>
    <?php endif; ?>
</div>