<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoAltText
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Generate Album template
 *
 * @var $block \Bss\SeoAltText\Block\Adminhtml\GenerateAlbum
 */
?>
<?php
$totalLink = $block->getTotalLink();
$ajaxLink = $block->getLinkAjax();
$crawlLink = $block->getLinkCrawl();
$backLink = $block->getBackLink();
$maxLinkCrawl = \Bss\SeoAltText\Helper\Data::SEO_ALT_TEXT_PER_PAGE;
$statusEnable = $block->getDataHelper()->isEnableModuleByDefault();
$dataJson = [
    "totalLink" => $totalLink,
    "ajaxLink" => $ajaxLink,
    "crawlLink" => $crawlLink,
    "maxLink" => $maxLinkCrawl,
    "statusEnable" => $statusEnable
];
$dataJsonEncode = $block->getDataHelper()->jsonEncode($dataJson);
?>
<div class="seo_report_header_crawl">
    <div class="seo_report_button" id="bss_seo_report_start_crawl"><?= __("Start Generating"); ?></div>
    <a href="<?= $block->escapeUrl($backLink); ?>">
        <div class="seo_report_button right"><?= __("Go To SEO Alt Text"); ?></div>
    </a>
</div>
<div class="seo_report_body_crawl">
    <div class="seo_report_process_crawl">
        <div class="seo_report_percent_crawl" id="seo_report_percent_crawl"></div>
    </div>
    <div class="seo_report_show_crawl">
        <div class="seo_report_show_crawl_child" id="seo_report_show_crawl_child">
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_SeoAltText/js/generate": <?= $dataJsonEncode; ?>
        }
    }
</script>
