<?php
/**
 * @copyright Copyright © 2020 Magepow. All rights reserved.
 * @author    @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
?>
<?php
/**
 * @var $block \Magepow\OnestepCheckout\Block\LayoutOnestep\Container
 */
?>
<p class="checkout-description">
    <?php echo $block->getCheckoutDescription(); ?>
</p>
