<?php
namespace Codedecorator\WhatsAppChat\Block;

use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\View\Element\Template;
use Codedecorator\WhatsAppChat\Helper\Data;
use Magento\Framework\UrlInterface;
class WhatsAppChat extends Template
{
    protected $helper;
    public function __construct(Template\Context $context, Data $helper, array $data = [])
    {
        $this->helper = $helper;
        $this->addData([
            'cache_lifetime' => 1
        ]);
        parent::__construct($context, $data);
    }
    public function getConfigData(){
        try {
            $storeId = $this->_storeManager->getStore()->getId();
            $config = $this->helper->getWhatsAppData($storeId);
            $config['image'] = $this->_storeManager->getStore()->getBaseUrl(UrlInterface::URL_TYPE_MEDIA).'whatsapp/'.$config['image'];
            return $config;
        } catch (NoSuchEntityException $e) {
            return false;
        }

    }
    public function getCacheLifetime()
    {
        return null; // TODO: Change the autogenerated stub
    }
}