<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Breadcrumbs
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$crumbs = $viewModel->getCrumbs();
$breadcrumbsSeo = $viewModel->getBreadcrumbsBlock(); // This get custom seo suite block
?>
<?php if ($breadcrumbsSeo->isProductInSingleCat()): ?>
    <?php if ($crumbs && is_array($crumbs)) : ?>
        <div class="breadcrumbs">
            <ul class="items">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else : ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="breadcrumbs"></div>
    <?php
        $widgetOptions = $breadcrumbsSeo->getBreadCrumbsOptions();
    ?>
    <script type="text/x-magento-init">
        {
            ".breadcrumbs": {
                "breadcrumbs": <?= /* @noEscape */ $widgetOptions ?>
            }
        }
    </script>
<?php endif; ?>