<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_RichSnippets
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * General Block
 * @var $block Bss\RichSnippets\Block\Product
 */
?>
<?php
$typePage = $block->getTypePage();
$pageTitle = $block->getTitlePage();
$mediaUrl = $block->getMediaUrl();
$helper = $block->getHelper();
$twitterUser = $helper->getTwitterUser();
$getEnable = $helper->getEnableForWebsite();
$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$websiteDescription = $helper->getWebsiteDescription();
$websiteImage = $helper->getWebsiteImage();
$websiteImage = $mediaUrl . 'bss/logo/' . $websiteImage;
$getEnableTwitter = $helper->getEnableForWebsiteT();
if ($typePage != 'catalog_product_view' && $typePage != 'catalog_category_view' && $getEnable == '1') : ?>
    <meta property="og:type" content="og:product" />
    <meta property="og:title" content="<?= $block->escapeHtml($pageTitle); ?>" />
    <meta property="og:image" content="<?= $block->escapeUrl($websiteImage); ?>" />
    <meta property="og:description" content="<?= $block->escapeHtml($websiteDescription); ?>" />
    <meta property="og:url" content="<?= $block->escapeHtml($block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])); ?>" />
    <?php
endif; ?>
<?php if ($typePage != 'catalog_product_view' && $typePage != 'catalog_category_view' && $getEnableTwitter == '1') : ?>
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="<?= $block->escapeHtml($twitterUser); ?>" />
    <meta name="twitter:title" content="<?= $block->escapeHtml($pageTitle); ?>" />
    <meta name="twitter:description" content="<?= $block->escapeHtml($websiteDescription); ?>" />
    <meta name="twitter:image" content="<?= $block->escapeUrl($websiteImage); ?>" />
    <?php
endif; ?>
<?php
$baseUrl = $block->getBaseUrl();
$fileUrl = $helper->getFileUrl();
$searchBox = $helper->getSearchBox();
$websiteName = $helper->getWebsiteName();
$enableSiteName = $helper->getEnableWebsite();
$companyName = $helper->getCompanyName();
$companyPriceRange = $helper->getComapnyPriceRange();
$companyEmail = $helper->getCompanyEmail();
$companyTelephone = $helper->getCompanyTelephone();
$companyAddress = $helper->getCompanyAddress();
$companyStreet = $helper->getCompanyStreet();
$companySocial = $helper->getCompanySocial();
$companyCountry = $helper->getCompanyCountry();
$companyPostCode = $helper->getCompanyPostCode();
$imageUrl = $mediaUrl . 'bss/logo/' . $fileUrl;

$companyEnable = $helper->isSetFlag(\Bss\RichSnippets\Helper\Data::BSS_RICH_ENABLE_COMPANY);
$localType = $helper->getConfig(\Bss\RichSnippets\Helper\Data::BSS_RICH_LOCAL_TYPE);
if (!$localType) {
    $localType = 'LocalBusiness';
}
if ($companySocial != null) {
    $companySocial = explode("\n", $companySocial);
}

$dataLocal = [
    "@context" => "http://schema.org",
    "@type" => $block->escapeHtml($localType),
    "@id" => $block->escapeHtml($baseUrl),
    "name" => $block->escapeHtml($companyName),
    "image" => $block->escapeUrl($imageUrl),
    "email" => $block->escapeHtml($companyEmail),
    "priceRange" => $block->escapeHtml($companyPriceRange),
    "address" => [
        "@type" => "PostalAddress",
        "streetAddress" => $block->escapeHtml($companyStreet),
        "addressLocality" => $block->escapeHtml($companyAddress),
        "postalCode" => $block->escapeHtml($companyPostCode),
        "addressCountry" => $block->escapeHtml($companyCountry)
    ],
    "telephone"=> $block->escapeHtml($companyTelephone)
];
$dataJsonLocal = $helper->jsonEncode($dataLocal);

$dataCompanySocial = []
?>
<?php if ($enableSiteName == '1') : ?>
    <?= '<script type="application/ld+json">'; ?>
    {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "name": "<?= $block->escapeHtml($websiteName); ?>",
        "url": "<?= $block->escapeUrl($baseUrl); ?>"<?php
        if ($searchBox == '1') :
            ?>,
        "potentialAction": {
            "@type": "SearchAction",
            "target": "<?= $block->escapeHtml($block->getResultUrl()); ?>?q={search_term_string}",
            "query-input": "required name=search_term_string"
        }<?php
        endif; ?>
    }
    </script>

<?php endif; ?>
<?php if ($companyEnable) : ?>
    <?= '<script type="application/ld+json">'; ?>
        <?= $dataJsonLocal ?>
    <?= '</script>' ?>
    <?php
endif; ?>
<?php if ($companySocial != null && $companyEnable) : ?>
    <?= '<script type="application/ld+json">'; ?>
    {
        "@context": "http://schema.org",
        "@type": "Person",
        "name": "<?= $block->escapeHtml($companyName); ?>",
        "url": "<?= $block->escapeUrl($baseUrl); ?>",
        "sameAs": [
            <?php
            foreach ($companySocial as $key => $value) : ?>
                <?php if ($key == '0') :
                    ?>"<?= $block->escapeHtml($value); ?>"
                <?php else :
                    ?>,"<?= $block->escapeHtml($value); ?>"
                <?php endif; ?>
            <?php endforeach; ?>
            ]
        }
    </script>
    <?php
endif;
