<a href="#" class="sidebar-filters-toggle custom-mobile-filter-section">
	<svg data-name="sidebar-filter-toggle" class="filter-toggle" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
		<line class="cls-1" x1="15" x2="26" y1="9" y2="9"></line>
		<line class="cls-1" x1="6" x2="9" y1="9" y2="9"></line>
		<line class="cls-1" x1="23" x2="26" y1="16" y2="16"></line>
		<line class="cls-1" x1="6" x2="17" y1="16" y2="16"></line>
		<line class="cls-1" x1="17" x2="26" y1="23" y2="23"></line>
		<line class="cls-1" x1="6" x2="11" y1="23" y2="23"></line>
		<path class="cls-2" d="M14.5,8.92A2.6,2.6,0,0,1,12,11.5,2.6,2.6,0,0,1,9.5,8.92a2.5,2.5,0,0,1,5,0Z"></path>
		<path class="cls-2" d="M22.5,15.92a2.5,2.5,0,1,1-5,0,2.5,2.5,0,0,1,5,0Z"></path>
		<path class="cls-3" d="M21,16a1,1,0,1,1-2,0,1,1,0,0,1,2,0Z"></path>
		<path class="cls-2" d="M16.5,22.92A2.6,2.6,0,0,1,14,25.5a2.6,2.6,0,0,1-2.5-2.58,2.5,2.5,0,0,1,5,0Z"></path>
	</svg>
	<span class="custom-filter-btn-view">
	<span class="title-filter-toggle"><?php echo __('Filters') ?></span>
	<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
          <path d="M16.5 2.25H1.5L7.5 9.345V14.25L10.5 15.75V9.345L16.5 2.25Z" stroke="#535865" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
	</span>
</a>
