<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Custom Reports Builder for Magento 2
 */
/** @var \Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Amasty\ReportBuilder\ViewModel\Adminhtml\View\Sidebar $viewModel */

$viewModel = $block->getData('view_model');
$sidebarData = $viewModel->getMenuDataJson();
$currentReportId = $viewModel->getCurrentReportId();
$jsLayout = $viewModel->prepareJsLayout($block->getData());
?>

<aside class="amrepbuilder-sidebar-wrapper"
       data-bind="
            scope: 'amrepbuilder_sidebar_source',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        'amrepbuilder_sidebar_source': {
                            component: 'uiComponent',
                            sidebarData: <?= $escaper->escapeHtml($sidebarData) ?>,
                            currentReportId: <?= $escaper->escapeHtml($currentReportId) ?>,
                            children: <?= $escaper->escapeHtml($jsLayout) ?>
                        }
                    }
                }
            }">

    <!-- ko scope: "index = amrepbuilder_sidebar_wrapper" -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->

    <!-- ko scope: "index = amrepbuilder_sidebar_loader" -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->

    <!-- ko scope: "index = amrepbuilder_sidebar_popup" -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</aside>
