<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Custom Reports Builder for Magento 2
 */
/** @var \Amasty\ReportBuilder\Block\Adminhtml\Widget\Form\Renderer\DefaultElement $block */
/** @var \Magento\Framework\Escaper $escaper */

$element = $block->getElement();
?>

<div class="amrepbuilder-field <?= $escaper->escapeHtmlAttr($element->getWrapperClass()) ?>">
    <?= /* @noEscape */ $element->getLabelHtml() ?>
    <?= /* @noEscape */ $element->getElementHtml() ?>
</div>
