<?php
/**
 * Magedelight
 * Copyright (C) 2022 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2022 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */

/**
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php
$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$smsProfileHelper = $block->getData('view_model');
$smsProfileHelper = $smsProfileHelper->getHelperData();
$otpLogin = $smsProfileHelper->getSmsProfileOtpOnLogin();
$validate = $smsProfileHelper->getSmsProfileMailPhoneValidationClass();
if ($smsProfileHelper->getModuleStatus()) {
    $autoVerifyOTP =  $smsProfileHelper->getAutoGenerateLogin();
    $otpLength = $smsProfileHelper->getOtpLength();
    $resendLimitEnable=$smsProfileHelper->getOTPResendLimitEnable();
    $resendLimit=$smsProfileHelper->getOTPResendLimit();
    $resendLimitTime=$smsProfileHelper->getResendTime();
    $resendCount=$smsProfileHelper->getCustomCookie('resend_count');
    $datetime_1 =$smsProfileHelper->getCustomCookie('resend_count_time');
   
    $disableResendLink=0;
    if($resendLimit == $resendCount || $resendCount > $resendLimit){
        $disableResendLink=1;
    }

    $phoneValidation = $smsProfileHelper->getPhoneValidation();

    $mobileNumberFieldClass = 10;
    if(!$smsProfileHelper->isCustomerCountryEnabled()){
        for ($i=0; $i < count($phoneValidation); $i++) { 
            if ($phoneValidation[$i]['country']=='default') {
                $mobileNumberFieldClass = $phoneValidation[$i]['digit'];
            }  
        }
    }
}
?>
<div class="login-container signup-container">
    <div class="block">
        <div class="block-title">
            <h3><strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Forgot Password')) ?></strong></h3>
        </div>
        <form class="form password forget md-forget-password"
              action="<?= $block->escapeUrl($block->getUrl('customer/account/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
                <?php if(in_array($otpLogin, ['login_both','login_otp']) && $smsProfileHelper->getModuleStatus()): ?>
                    <input type='hidden' name='form_type' id="form_type" value="<?= $block->escapeHtml(__('forgot')) ?>"/>   
                    <input type='hidden' name='auto_verify_otp' id="auto_verify_otp" value="<?= $block->escapeHtml($autoVerifyOTP) ?>"/>
                    <input type='hidden' name='opt_code_limit' id="opt_code_limit" value="<?= $block->escapeHtml($otpLength) ?>"/>
                    <input type='hidden' name='resend_limit' id="resend_limit" value="<?= $block->escapeHtml($resendLimit) ?>"/>
                    <input type='hidden' name='resend_limit_time' id="resend_limit_time" value="<?= $block->escapeHtml($resendLimitTime) ?>"/>
                    <input type='hidden' name='resend_link_disable' id="resend_link_disable" value="<?= $block->escapeHtml($disableResendLink) ?>"/>
                    <input type='hidden' id="phone_validation" name="phone_validation" value="<?= $escaper->escapeHtmlAttr(json_encode($phoneValidation)) ?>"/>
                    <?php if(!$smsProfileHelper->isCustomerCountryEnabled()):?>
                        <input type="hidden" id="default_mobile_validation" value="<?= $escaper->escapeHtmlAttr($mobileNumberFieldClass);?>" />
                    <?php endif;?>
                    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <?php if(in_array($otpLogin, ['login_both'])): ?>
                             <?= /* @noEscape */ $secureRenderer->renderTag('style', [], ".iti__flag-container{display: none;}", false) ?>
                            <div class="smsprofile-login-option">
                                <div class="login-option-tab">
                                    <div class="login-mobile active" data-md-js="md-login-opt">
                                        <input type="button" class="login-opt " name="Mobile" id="login-opt-mobile" value="<?= $block->escapeHtml(__('Reset with OTP')) ?>" />
                                    </div>
                                    <div class="login-email " data-md-js="md-login-password">
                                        <input type="button" class="login-opt" name="Email" id="login-opt-email" value="<?= $block->escapeHtml(__('Reset with Email')) ?>" />
                                    </div>
                                </div>
                            </div>
                        <?php endif;?> 
                        <div class="field email required block-customer-login" id="forgot-email-content" style="display:none">
                            <div class="form-field">
                                <div class="form-field__control">
                                    <!-- <label for="email_address" class="label form-field__label"><span><?= $block->escapeHtml(__('Email')) ?></span></label> -->
                                    <div class="control">
                                        <input type="email" name="email" alt="email" id="email_address" placeholder="Email Address" class="input-text form-field__input" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field mobile required smsprofile-login-mobile" id="forgot-mobile-content">
                            <div class="control">
                                <input type="hidden" value="" id="countryreg" name="countryreg" class="countrycodeval" />
                                <input type="hidden" value="" id="countryregcode" name="countryregcode" />
                                <input type="text" name="customer_mobile" alt="<?= $block->escapeHtml(__('Mobile Number')) ?>" id="login_mobile" placeholder="<?= $block->escapeHtml(__('Enter Email/Mobile number')) ?>" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{},"validation":{}}' data-validate="{required:true}">
                            </div>
                            <?php if($smsProfileHelper->getPhoneNote()):?>
                                <div class="profile-notice-phone">
                                    <span><?= $smsProfileHelper->getPhoneNote(); ?></span>
                                </div>
                            <?php endif; ?>
                            <div class="field">
                                    <button class="send_otp_login action primary" style="display: none;" type="button"><?= __('Generate OTP');?></button>
                                    <span class="otp_generatenote">&nbsp;</span>
                                <div class="resendotp-block" style="display: none">
                                    <?php if($resendLimitEnable == 1):?>
                                        <p class="resend-wait">
                                            <?= __('Resend In:'); ?>
                                            <span class="time"><?= ' '.$resendLimitTime; ?></span> <?= __('Seconds'); ?>
                                        </p>
                                        <div class="resendlink" style="display: none">
                                             <button class="resendotp"  type="button"><?= __('Resend OTP');?></button>
                                        </div>
                                        <div class="resend-link-attempt" style="display: none"></div>
                                    <?php endif; ?>
                                    <div class="field field-name-otp required">
                                        <label class="label" for="otp">
                                            <span><?= __('Please enter verification code here'); ?></span>
                                        </label>
                                        <div class="control">
                                            <input id="otp" name="otp" value="" title="otp"
                                                   class="input-text required-entry" data-validate="{required:true}"
                                                   autocomplete="off" aria-required="true" type="text"
                                                   novalidate="novalidate" style="width: 200px;">
                                                
                                            <button class="verif_otp_login action primary"
                                                    type="button"><?= __('Verify OTP'); ?></button>
                                            
                                        </div>
                                    </div>
                                </div>
                                <span class="otp_text"></span>
                                <span class="smserror" style="color: red;">&nbsp;</span>
                            </div>
                            <input type='hidden' name='forgetOtpValidation' class='verifiedotp' value="<?= $escaper->escapeHtmlAttr('0') ?>"/>
                            <input type='hidden' class='verifiedotpval' name = 'forgetOtpVal' value="<?= $block->escapeHtml('0') ?>"/>
                            <?php if($smsProfileHelper->getRecaptchaStatus() && in_array('forgot', $smsProfileHelper->getRecaptchaForms())):?>
                            <div id="forgot-captcha"></div>
                            <input type="hidden" id="captcha-response" name="captcha-response" />
                            <input type="hidden" id="captcha-widget-id" name="captcha-widget-id" />
                        <?php endif;?>
                        </div>
                        <div class="md_reset_password" style="display: none;">
                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                <div class="form-field">
                                    <div class="form-field__control">
                                        <label class="label form-field__label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                                        <div class="control">
                                            <input type="password" class="input-text form-field__input" name="password" id="password"
                                                   data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                                   data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                                   data-validate="{required:true, 'validate-customer-password':true}"
                                                   autocomplete="off">
                                            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                                <div id="password-strength-meter" class="password-strength-meter">
                                                    <?= $block->escapeHtml(__('Password Strength')) ?>:
                                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                                    <?= $block->escapeHtml(__('No Password')) ?>
                                                     </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field confirmation required">
                                <div class="form-field">
                                    <div class="form-field__control">
                                        <label class="label form-field__label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                                        <div class="control">
                                            <input type="password" class="input-text form-field__input" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'.md_reset_password #password'}" autocomplete="off">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                    </fieldset>
                    <div class="actions-toolbar reset-pwd">
                        <div class="primary">
                            <button type="submit" id="send2" class="action submit primary" data-md-js="md-submit-button" disabled="disabled"><span><?= $block->escapeHtml(__('Reset Password')) ?></span></button>
                        </div>
                    </div>
                    <?php if($smsProfileHelper->isCustomerCountryEnabled()): ?>
                        <script type="text/x-magento-init">
                            {
                                "input[name='customer_mobile']": {
                                    "Magedelight_SMSProfile/js/intlTelephoneInput":
                                        {
                                            "nationalMode":true,
                                            "separateDialCode": true,
                                            "utilsScript":"<?= $this->getViewFileUrl('Magedelight_SMSProfile::js/utils.js'); ?>",
                                            "preferredCountries":["<?= $smsProfileHelper->getDefaultCustomerCountry(); ?>"],
                                            "onlyCountries":[<?= $smsProfileHelper->getAvailableCountries(); ?>]
                                        }
                                }
                            }
                        </script>
                    <?php endif; ?>
                    <?php if(str_contains($currentUrl,'customer/account/forgotpassword/')):?>
                        <script type="text/x-magento-init">
                        {
                            "*": {
                                "Magedelight_SMSProfile/js/custom-login" : {
                                }
                            }
                        }
                        </script>
                    <?php endif;?>
                <?php else:?>
                    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                        <div class="field email required">
                            <div class="control">
                                <input type="email" placeholder="Email Address" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                    </fieldset>
                    <div class="actions-toolbar reset-pwd">
                        <div class="primary">
                            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Send Email')) ?></span></button>
                        </div>
                        <div class="secondary">
                            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                        </div>
                    </div>
                <?php endif;?>
        </form>
    </div>
</div>
