<?php
/**
 * Magedelight
 * Copyright (C) 2022 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2022 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>
<?php
$smsProfileHelper = $this->helper('Magedelight\SMSProfile\Helper\Data');
?>
<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <input type="tel"
               name="telephone"
               id="telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $block->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               )?>"
             data-validate="{'validate-number':true}"
        >
        <?php if($smsProfileHelper->isCustomerCountryEnabled()): ?>
          <input type="hidden" name='login[countrycodeval]' value="" id="countryreg" name="countryreg" />
          <input type="hidden" value="" id="countryregcode" name="countryregcode" />
        <?php endif; ?>
    </div>
</div>
<?php if($smsProfileHelper->isCustomerCountryEnabled()): ?>
  <script type="text/x-magento-init">
    {
      "input[name='telephone'": {
      "Magedelight_SMSProfile/js/intlTelephoneInput":
      {
        "nationalMode":true,
        "separateDialCode": true,
        "utilsScript":"<?= $this->getViewFileUrl('Magedelight_SMSProfile::js/utils.js'); ?>",
        "preferredCountries":["<?= $smsProfileHelper->getDefaultCustomerCountry(); ?>"],
        "onlyCountries":[<?= $smsProfileHelper->getAvailableCountries(); ?>]
      }
    }
  }
</script>
<?php endif; ?>