<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showAddto = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $showAddto = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-products custom-products-list clearfix products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <!-- mode view list -->
                <?php if ($block->getMode() == 'list') : ?>
                    <div class="product-item-info category-products-list" data-container="product-grid">
                        <div class="product-item-details">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image 
                            ?>
                            <div class="images-container">
                                <?php
                                $product_label = $_aloHelper->getLabels($_product);
                                echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : '';
                                ?>
                                <div class="product-hover">
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>
                                    <div class="link-view">
                                        <button type="button" class="quickview <?php echo $_product->getTypeId() ?>" title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure' => $this->getRequest()->isSecure())) ?>'});"><span><i class="fa fa-eye icons"></i><?php echo __('Quick View') ?></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
    
                            <div class="product details details-container clearfix">
                                <div class="products-textlink clearfix">
                                    <?php if ($templateType) {
                                        $rating = $block->getReviewsSummaryHtml($_product, $templateType);
                                        if ($rating) {
                                            echo $rating;
                                        } else {
                                    ?>
                                            <div class="sdsd product-reviews-summary short">
                                                <div class="rating-summary">
                                                    <div class="rating-result" title="0%">
                                                        <span style="width:0%"><span>0%</span></span>
                                                    </div>
                                                </div>
                                                <div class="reviews-actions">
                                                    <a class="action view" tabindex="0">0 &nbsp;<span>Reviews</span></a>
                                                </div>
                                            </div>
                                    <?php }
                                    } ?>
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <h2 class="product name product-name product-item-name">
                                        <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </h2>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
    
                                    <?php if ($_product->getIsSalable()) : ?>
                                        <div class="stock available"><label><?php /* @escapeNotVerified */ echo __('Availability:') ?> </label><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else : ?>
                                        <div class="stock unavailable"><label><?php /* @escapeNotVerified */ echo __('Availability:') ?> </label><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
    
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    <?php if ($showAddto) : ?> <?php /* @showAddto */ ?>
                                        <div class="product-item-inner">
                                            <div class="product actions-no product-item-actions clearfix" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <div class="actions-primary" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_product->getIsSalable()) : ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div data-role="add-to-links" class="actions-secondary add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                        <a href="#" class="action towishlist link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                        <span><?php echo __('Add to Compare') ?></span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; /* End showAddto */ ?>
                                    <?php if ($showDescription) : ?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>" class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>    
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- and / mode view list -->
                <!-- mode view grid -->
                <?php if ($block->getMode() == 'grid') : ?>
                    <div class="product-item-info per-product category-products-grid" data-container="product-grid">
                        <div class="product-item-details">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <div class="images-container">
                                <?php
                                $product_label = $_aloHelper->getLabels($_product);
                                echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : '';
                                ?>
                                <div class="product-hover">
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>
                                </div>
                                </div>
                            </div>
                            <div class="product details details-container products-textlink">
                                <div class="custom-swatches-section">
                                  <?php echo $block->getProductDetailsHtml($_product); ?>
                                </div>

                                <?= $block->getReviewsSummaryHtml($_product, $templateType,true) ?>

                                
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h2 class="product name product-name product-item-name">
                                    <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h2>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                              
                               <div class="hover-box clearfix">
                                        <div class="product-item-inner actions clearfix">
                                            <div class="product product-item-actions show-box" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <div class="actions-primary actions-cart" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <?php
                                                            if (($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) || ($_product->getTypeId() == \Magento\Bundle\Model\Product\Type::TYPE_CODE) || ($_product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE)){
                                                                // Get the URL of the product page
                                                                $productUrl = $_product->getProductUrl();
                                                                //echo $productUrl;
                                                            ?>
                                                            <a class="action tocart1" href='<?php echo $productUrl ; ?>' title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </a>
                                                            <?php
                                                            }
                                                            else {
                                                            ?>
                                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart pull-left-none">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                            <?php
                                                            } ?>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_product->getIsSalable()) : ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div data-role="add-to-links" class="actions-secondary add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                        <a href="#" class="action towishlist link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                                        <div class="custom-wishlist-image"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                                                          <path d="M9.465 15.6075C9.21 15.6975 8.79 15.6975 8.535 15.6075C6.36 14.865 1.5 11.7675 1.5 6.51751C1.5 4.20001 3.3675 2.32501 5.67 2.32501C7.035 2.32501 8.2425 2.98501 9 4.00501C9.7575 2.98501 10.9725 2.32501 12.33 2.32501C14.6325 2.32501 16.5 4.20001 16.5 6.51751C16.5 11.7675 11.64 14.865 9.465 15.6075Z" stroke="#7E828B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                                        </svg></div>    
                                                        </a>
                                                    <?php endif; ?>
                                                    <a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                        <span><?php echo __('Add to Compare') ?></span>
                                                    </a>
                                                </div>
                                                <div class="link-view">
                                                    <button type="button" class="action quickview <?php echo $_product->getTypeId() ?>" title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure' => $this->getRequest()->isSecure())) ?>'});"><span><i class="fa fa-eye icons"></i><?php echo __('Quick View') ?></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- and / mode view grid -->
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom ">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
