<?php

/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post next and prev post links
 *
 * @var $block \Magefan\Blog\Block\Post\View\NextPrev
 */
?>

<?php if ($block->displayLinks()) { ?>
    <?php
    $prevPost = $this->getPrevPost();
    $nextPost = $this->getNextPost();
    ?>
    <?php if ($prevPost || $nextPost) { ?>
        <div class="post-nextprev-hld post-actions clearfix">
            <?php if ($prevPost) { ?>
                <?php
                $_prevPostUrl = $prevPost->getPostUrl();
                $_prevPostName = $block->escapeHtml($prevPost->getTitle(), null, true);
                ?>
                <?php $title = $block->escapeHtml($prevPost->getTitle()) ?>
                <div class="prev-action action">
                    <?php if ($featuredImage = $prevPost->getFeaturedImage()) { ?>
                        <div class="post-ftimg-hld">
                            <a class="blog-image" href=" <?php echo $_prevPostUrl ?>" title="<?php echo $_prevPostName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_prevPostName ?>" />
                            </a>
                        </div>
                    <?php } ?>
                    <a class="nextprev-link prev-link" href="<?php echo $prevPost->getPostUrl() ?>" title="<?php echo __('Read %1', $title) ?>">
                        <span><?php echo __('&larr; Previous Post') ?></span>
                        <span class="post-title"><?php echo $_prevPostName; ?></span>
                    </a>
                </div>
            <?php } ?>
            <?php if ($nextPost) { ?>
                <?php
                $_nextPostUrl = $nextPost->getPostUrl();
                $_nextPostName = $block->escapeHtml($nextPost->getTitle(), null, true);
                ?>
                <?php $title = $block->escapeHtml($nextPost->getTitle()) ?>
                <div class="next-action action">
                    <a class="nextprev-link next-link" href="<?php echo $nextPost->getPostUrl() ?>" title="<?php echo __('Read %1', $title) ?>">
                        <span><?php echo __('Next Post &rarr;') ?></span>
                        <span class="post-title"><?php echo $_nextPostName; ?></span>
                    </a>
                    <?php if ($featuredImage = $nextPost->getFeaturedImage()) { ?>
                        <div class="post-ftimg-hld">
                            <a class="blog-image" href="<?php echo $_nextPostUrl ?>" title="<?php echo $_nextPostName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_nextPostName ?>" />
                            </a>
                        </div>
                    <?php } ?>
                </div>

            <?php } ?>
        </div>
    <?php } ?>
<?php } ?>