<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoReport
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Seo Report Crawl
 * @var $block Bss\SeoReport\Block\System\Config\Login
 */
?>
<?php echo $block->getButtonHtml() ?>
<?php
$urlLogin = $block->getLoginUrl();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_SeoReport/js/google_authorization": {
                "client_id": "<?= $block->getClientId() ?>",
                "uris": "<?= $block->getUris() ?>"
        	}
        }
    }
</script>
