<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoReport
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
namespace Bss\SeoReport\Model\ResourceModel\ReportLinks;

/**
 * Class Collection
 * @package Bss\SeoReport\Model\ResourceModel\ReportLinks
 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    /**
     * @inheritdoc
     */
    protected function _construct()
    {
        $this->_init(
            \Bss\SeoReport\Model\ReportLinks::class,
            \Bss\SeoReport\Model\ResourceModel\ReportLinks::class
        );
    }

    /**
     * @return \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection|void
     * @throws \Zend_Db_Statement_Exception
     */
    protected function _initSelect()
    {
        parent::_initSelect();

        $this->getSelect()->joinLeft(
            ['storeTable' => $this->getTable('store')],
            'main_table.store_id = storeTable.store_id',
            []
        )->joinLeft(
            ['seoReport' => $this->getTable('bss_seo_report')],
            'main_table.url_rewrite_id = seoReport.url_rewrite_id',
            ['canonical_tag', 'headings', 'images', 'open_graph', 'twitter_card', 'expired']
        )->where(
            'storeTable.is_active = 1'
        )->where(
            "main_table.is_autogenerated = 1"
        )->group('main_table.request_path');
    }
}
