<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="product-info-base custom-wishlist-name-section">
    <strong class="product-item-name">
        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
            <?= $block->escapeHtml($product->getName()) ?>
        </a>
    </strong>
    
    <?= $block->getReviewsSummaryHtml($product, 'short') ?>
</div>

<div class="custom-avaibility-section">
    <?php if ($product->getIsSalable()) : ?>
    <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $block->escapeHtml(__('In stock')) ?></span>
    </p>
<?php else : ?>
    <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
    </p>
<?php endif; ?>
</div>