<script type="text/javascript">
    require(['jquery'], function($) {
     /*   var url = 'https://karzoun.app/assets/uploads/karzoun/Widget.js';
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = url;
        var options = {
          "enabled": true,
          "chatButtonSetting": {
              "backgroundColor": "#218365",
              "ctaText": "تواصل معنا",
              "borderRadius": "25",
              "marginLeft": "50",
              "marginBottom": "50",
              "marginRight": "50",
              "position": "right"
          },
          "brandSetting": {
              "brandName": "خدمة عملاء ليلت للأثاث",
              "brandSubTitle": "نقوم بالرد خلال ثوان",
              "brandImg": "https://cdn.salla.sa/form-builder/YAIOEtWIUHWbj9gXfGaL8dNV60nXdV6oAONnMWPY.png",
              "welcomeText": "مرحبا فيك عزيز وغالي علينا,</br>للطلب ارسل 1</br>لتتبع الطلب ارسل 2</br>للشكاوي ارسل 3",
              "messageText": "مرحبا اريد الإستفسار عن >> {page_link}",
              "backgroundColor": "#218365",
              "ctaText": "تواصل معنا",
              "borderRadius": "25",
              "autoShow": false,
              "phoneNumber": "966536080444"
          }
        };
        s.onload = function() {
            CreateWhatsappChatWidget(options);
        };
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);*/
    });
</script>
