<?php
/**
 * Magedelight
 * Copyright (C) 2022 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2022 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */
 
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<label class="admin__field-label" />
<div class="admin__field-control">    
    <?php echo $block->getGridHtml(); ?>
</div>
<script>
    require([ "jquery"], function($) {
        $("input[name='selectedcustomer[]']").attr('form','smspromotional_form');      
    });
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
     require('mage/apply/main').apply(); 
</script>