<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="contact-content custom-main-contact-us">
    <div class="form-primary">
        <div class="row">
            <div class="form-primary-item">
                <div class="store-contact">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store-contact')->toHtml();?>
                </div>
            </div>
            <div class=" form-primary-item">
                 <form class="form contactus" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                    <div class="form-contactus">
                         <fieldset class="fieldset">
                            
                            <div class="image-custom-section">
                                <span class="title-top-icon"><svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72" fill="none"> <path d="M12 12.0001H60C63.3 12.0001 66 14.7001 66 18.0001V54.0001C66 57.3001 63.3 60.0001 60 60.0001H12C8.7 60.0001 6 57.3001 6 54.0001V18.0001C6 14.7001 8.7 12.0001 12 12.0001Z" stroke="#282E3E" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M66 18.8574L36 39.8574L6 18.8574" stroke="#282E3E" stroke-linecap="round" stroke-linejoin="round"></path> </svg> </span>
                            </div>
                             <h3 class="block-title"><?php /* @escapeNotVerified */ echo __('Send message') ?></h3>
                            <div class="field info">
                                 <div class="field  name required">
                                    
                                    <div class="control">
                                           <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('First name') ?>"/>
                                           <label class="name"><?php echo __("First Name")?></label>
                                        </div>
                                 </div>
                                 <div class="field lastname required">
                                    <div class="control">
                                           <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Last name') ?>"/>
                                           <label class="lastname"><?php echo __("Last Name")?></label>
                                        </div>
                                 </div>
                            </div>
                            <div class="field info">
                                 <div class="field  email required">
                                     <div class="control">
                                        <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Your Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Your email') ?>"/>
                                        <label class="email" ><?php echo __("Email Address")?></label>
                                    </div>
                                 </div>
                                 <div class="field contactnumber required">
                                    <div class="control">
                                           <input name="contactnumber" id="contactnumber" title="<?php /* @escapeNotVerified */ echo __('Contact Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="number" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Contact Number') ?>"/>
                                           <label  class="contactnumber"><?php echo __("Contact Number")?></label>
                                        </div>
                                 </div>
                            </div>
                            <div class="field   comment required">
                                 <div class="control">
                                     <textarea rows="10" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Your Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Your question here...') ?>"></textarea>
                                     <label class="comment" ><?php echo __("Your Message")?></label>
                                    </div>
                            </div>
                            <?php echo $block->getChildHtml('form.additional.info'); ?>
                             <div class="actions-toolbar">
                                <div class="primary">
                                    <input type="hidden" name="hideit" id="hideit" value="" />
                                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
                                    </button>
                                 </div>
                             </div>
                        </fieldset>
                    </div>
                </form>                    
            </div>
        </div>
    </div>
</div>

<!-- Messenger Plugin chat Code -->
<div id="fb-root"></div>

<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>